services:
  animearr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: animearr
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TZ
    volumes:
      - /home/user/docker/anime/sonarr:/config
      - /mnt/storage/Media/Anime:/anime
    ports:
      - 9898:8989
    restart: unless-stopped

  renamerr:
    build:
      context: ./renamerr
      dockerfile: Dockerfile
    container_name: renamerr
    environment:
      - SONARR_API_URL=http://animearr:8989/api/v3
      - SONARR_API_KEY=$API
      - PUID=$UID
      - PGID=$GID
    volumes:
      - /mnt/storage/Media/Anime:/anime
      - /home/user/docker/anime/renamerr/config:/config
    ports:
      - 5000:5000
    depends_on:
      - animearr

networks:
  default:
    name: downloads
    external: true
